package govrun

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/diktahq/edikt/tools/edikt/internal/phasea"
	"github.com/diktahq/edikt/tools/edikt/internal/phaseb"
	"github.com/diktahq/edikt/tools/edikt/internal/sidecar"
	"github.com/diktahq/edikt/tools/edikt/model"
)

// TwoPhaseOptions configures one invocation of the sidecar-aware compile.
type TwoPhaseOptions struct {
	ProjectRoot string
	CheckOnly   bool
	NoWait      bool
	Runner      phasea.Runner // injectable for tests; defaults to ClaudeRunner
	Concurrency int           // defaults to 8 per ADR-028
	Stderr      io.Writer
	Stdout      io.Writer
}

// TwoPhaseResult summarizes the run.
type TwoPhaseResult struct {
	StaleSidecars  []string
	PhaseADone     bool
	PhaseAFailures int
	PhaseB         *phaseb.Result
}

// RunTwoPhase is the sidecar-aware compile path per ADR-027 + ADR-028.
//
// Order of operations:
//  1. acquire .edikt/state/compile.lock (blocks unless --no-wait)
//  2. discover artifact pairs and detect stale sidecars
//  3. if --check && stale → emit actionable error, exit 1, no LLM dispatch
//  4. if stale && !--check → run Phase A (parallel resync, continue-on-error)
//  5. if Phase A had failures → exit 1, do NOT run Phase B (per ADR-028)
//  6. run Phase B (deterministic merge)
func RunTwoPhase(opts TwoPhaseOptions, clk model.Clock) (*TwoPhaseResult, error) {
	if opts.Stderr == nil {
		opts.Stderr = os.Stderr
	}
	if opts.Stdout == nil {
		opts.Stdout = os.Stdout
	}
	if opts.Concurrency <= 0 {
		opts.Concurrency = 8
	}
	if opts.Runner == nil {
		opts.Runner = &phasea.ClaudeRunner{}
	}

	cfg, err := loadConfig(opts.ProjectRoot)
	if err != nil {
		return nil, err
	}
	dirs := []string{cfg.Paths.Decisions, cfg.Paths.Invariants, cfg.Paths.Guidelines}

	release, err := acquireCompileLock(opts.ProjectRoot, opts.NoWait)
	if err != nil {
		return nil, err
	}
	defer release()

	pairs, err := sidecar.Discover(opts.ProjectRoot, dirs)
	if err != nil {
		return nil, fmt.Errorf("discover sidecars: %w", err)
	}

	res := &TwoPhaseResult{}
	var tasks []phasea.Task
	var loadErrs []string

	for _, p := range pairs {
		if p.LoadErr != nil {
			loadErrs = append(loadErrs, fmt.Sprintf("  %s: %v", p.SidecarPath, p.LoadErr))
			continue
		}
		if p.Sidecar == nil {
			loadErrs = append(loadErrs, fmt.Sprintf("  %s: sidecar missing — run /edikt:%s:compile", p.ParentPath, artifactTypeFromPath(p.ParentPath, dirs)))
			continue
		}
		stale, reason, err := p.Sidecar.IsStale(opts.ProjectRoot)
		if err != nil {
			loadErrs = append(loadErrs, fmt.Sprintf("  %s: %v", p.SidecarPath, err))
			continue
		}
		if stale {
			res.StaleSidecars = append(res.StaleSidecars, p.ArtifactID)
			tasks = append(tasks, phasea.Task{
				ArtifactType: artifactTypeFromPath(p.ParentPath, dirs),
				ArtifactID:   p.ArtifactID,
				ParentPath:   p.ParentPath,
				SidecarPath:  p.SidecarPath,
			})
			fmt.Fprintf(opts.Stderr, "  stale: %s — %s\n", p.ArtifactID, reason)
		}
	}

	if len(loadErrs) > 0 {
		fmt.Fprintln(opts.Stderr, "Sidecar errors:")
		for _, e := range loadErrs {
			fmt.Fprintln(opts.Stderr, e)
		}
		return res, fmt.Errorf("%d sidecar error(s)", len(loadErrs))
	}

	if opts.CheckOnly && len(tasks) > 0 {
		fmt.Fprintf(opts.Stderr, "error: %d sidecar(s) stale — run 'edikt gov compile' to resync\n", len(tasks))
		return res, fmt.Errorf("stale sidecars in --check mode")
	}

	if len(tasks) > 0 {
		ctx := context.Background()
		dis := &phasea.Dispatcher{
			Runner:       opts.Runner,
			Concurrency:  opts.Concurrency,
			ProgressOut:  opts.Stderr,
			ErrorLogPath: filepath.Join(opts.ProjectRoot, ".edikt", "state", "compile-errors.log"),
		}
		paRes := dis.Run(ctx, tasks)
		res.PhaseADone = true
		res.PhaseAFailures = len(paRes.Failures)
		fmt.Fprintf(opts.Stderr, "Phase A done: %d ok, %d failed in %s\n",
			paRes.TaskCount-len(paRes.Failures), len(paRes.Failures), paRes.Wall.Round(time.Millisecond))

		if len(paRes.Failures) > 0 {
			fmt.Fprintf(opts.Stderr, "Phase A failures (logged to .edikt/state/compile-errors.log):\n")
			for _, f := range paRes.Failures {
				fmt.Fprintf(opts.Stderr, "  %s: %v\n", f.Task.ArtifactID, f.Err)
			}
			return res, fmt.Errorf("phase A: %d failure(s); not running phase B", len(paRes.Failures))
		}

		// Reload sidecars now that they have been regenerated by subagents.
		pairs, err = sidecar.Discover(opts.ProjectRoot, dirs)
		if err != nil {
			return res, fmt.Errorf("rediscover after phase A: %w", err)
		}
	}

	if opts.CheckOnly {
		return res, nil
	}

	pbRes, err := phaseb.Merge(opts.ProjectRoot, pairs, phaseb.Options{
		CompiledAt:      clk.Now().Format(time.RFC3339),
		CompilerVersion: CompilerVersion,
	})
	if err != nil {
		return res, fmt.Errorf("phase B: %w", err)
	}
	res.PhaseB = pbRes

	fmt.Fprintf(opts.Stdout, "Phase B — merged %d sidecar(s) into %d topic file(s) (%d rendered, %d unchanged), index %s\n",
		len(pairs),
		len(pbRes.TopicsRendered)+len(pbRes.TopicsUnchanged),
		len(pbRes.TopicsRendered),
		len(pbRes.TopicsUnchanged),
		writtenLabel(pbRes.IndexWritten),
	)
	return res, nil
}

// artifactTypeFromPath returns "adr", "invariant", or "guideline" based on
// which configured dir the parent .md sits under.
func artifactTypeFromPath(parentPath string, dirs []string) string {
	abs, _ := filepath.Abs(parentPath)
	if strings.Contains(abs, string(os.PathSeparator)+"decisions"+string(os.PathSeparator)) {
		return "adr"
	}
	if strings.Contains(abs, string(os.PathSeparator)+"invariants"+string(os.PathSeparator)) {
		return "invariant"
	}
	if strings.Contains(abs, string(os.PathSeparator)+"guidelines"+string(os.PathSeparator)) {
		return "guideline"
	}
	for _, d := range dirs {
		if strings.Contains(parentPath, d) {
			if strings.Contains(d, "decisions") {
				return "adr"
			}
			if strings.Contains(d, "invariants") {
				return "invariant"
			}
			if strings.Contains(d, "guidelines") {
				return "guideline"
			}
		}
	}
	return "adr"
}

func writtenLabel(b bool) string {
	if b {
		return "rewritten"
	}
	return "unchanged"
}

// acquireCompileLock takes an advisory flock on .edikt/state/compile.lock.
// When noWait is true, contention returns an error immediately rather than
// blocking. The returned func releases the lock and removes the file (best
// effort).
func acquireCompileLock(projectRoot string, noWait bool) (func(), error) {
	lockDir := filepath.Join(projectRoot, ".edikt", "state")
	if err := os.MkdirAll(lockDir, 0o755); err != nil {
		return nil, fmt.Errorf("mkdir lock dir: %w", err)
	}
	lockPath := filepath.Join(lockDir, "compile.lock")
	f, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR, 0o644)
	if err != nil {
		return nil, fmt.Errorf("open lock file: %w", err)
	}
	how := syscall.LOCK_EX
	if noWait {
		how |= syscall.LOCK_NB
	}
	if err := syscall.Flock(int(f.Fd()), how); err != nil {
		f.Close()
		if noWait {
			return nil, fmt.Errorf("compile already running (lock held); --no-wait set, exiting")
		}
		return nil, fmt.Errorf("acquire compile.lock: %w", err)
	}
	return func() {
		_ = syscall.Flock(int(f.Fd()), syscall.LOCK_UN)
		_ = f.Close()
	}, nil
}
