#!/bin/bash
set -euo pipefail
# SessionStart hook: regenerate guide if verikt.yaml changed.
# Generated by verikt guide. Do not edit manually.

if [ ! -f "verikt.yaml" ]; then
  exit 0
fi

# Hash-based staleness detection.
HASH_FILE=".verikt/.guide-hash"
CURRENT_HASH=$(shasum -a 256 verikt.yaml | cut -d' ' -f1)
STORED_HASH=$(cat "$HASH_FILE" 2>/dev/null || echo "")

if [ "$CURRENT_HASH" = "$STORED_HASH" ]; then
  exit 0  # guide is fresh
fi

if verikt guide --target claude 2>/dev/null; then
  mkdir -p .verikt
  TMP_HASH=$(mktemp "$HASH_FILE.XXXXXX")
  echo "$CURRENT_HASH" > "$TMP_HASH"
  mv "$TMP_HASH" "$HASH_FILE"
  echo "{\"additionalContext\": \"verikt guide regenerated — architecture rules updated.\"}"
fi
exit 0
