package phaseb

// manifest.go — the render manifest.
//
// WHAT IT IS FOR
//
// One file listing every surface this compile produced, each with the SHA-256
// of its bytes. Three consumers need it and none of them can be served by
// walking the tree:
//
//   - ORPHAN CLEANUP (AC-2.5) needs to know what the LAST compile wrote, so a
//     surface belonging to a topic that has since disappeared can be deleted.
//     A tree walk cannot distinguish an orphan from a file someone added.
//   - RENDER FRESHNESS (AC-2.9) needs to know what the rendered tree SHOULD
//     hash to, so `--check` can say the tree is stale rather than clean.
//   - ROLLBACK (AC-2.8) needs the exhaustive list of what to remove. A
//     rollback that misses the directive index leaves it issuing MUST-grade
//     denies from governance that no longer exists.
//
// WHY IT CARRIES NO TIMESTAMP
//
// ADR-020 makes byte-determinism non-negotiable, and this file is the one most  edikt-guard:allow
// tempting to stamp — it is a build record, and build records conventionally
// say when they were built. A `generated_at` here would change the manifest's
// bytes on every no-op compile, which defeats every consumer above: freshness
// checking cannot distinguish "stale" from "recompiled", and the manifest
// would be permanently dirty in git.
//
// WHY THE MANIFEST DOES NOT HASH ITSELF
//
// It cannot: writing the hash changes the bytes being hashed. It is excluded
// explicitly rather than by accident, so a reader does not mistake its absence
// for an oversight and "fix" it.

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"sort"
	"strings"
)

// ManifestName is the manifest's basename inside the governance output dir.
const ManifestName = "manifest.yaml"

// ManifestEntry is one rendered surface and the hash of its bytes.
type ManifestEntry struct {
	Kind  string
	Path  string
	Topic string
	SHA   string
}

// hashFile returns the hex SHA-256 of a file's bytes.
//
// A MISSING file is an error, never an empty hash. An empty-string hash would
// compare equal to another missing file and make two absent surfaces look
// consistent with each other (INV-013).  edikt-guard:allow
func hashFile(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:]), nil
}

// BuildManifest hashes every enumerated surface.
//
// The manifest itself is skipped — it cannot contain its own hash — and so is
// any surface that vanished between render and hashing, which is reported as
// an error rather than silently omitted: a manifest that quietly lists fewer
// surfaces than were rendered is how an orphan becomes invisible.
func BuildManifest(root string, surfaces []Surface) ([]ManifestEntry, error) {
	out := make([]ManifestEntry, 0, len(surfaces))
	for _, s := range surfaces {
		if strings.HasSuffix(s.Path, ManifestName) {
			continue
		}
		abs := s.Path
		if !strings.HasPrefix(abs, "/") {
			abs = root + "/" + s.Path
		}
		sum, err := hashFile(abs)
		if err != nil {
			return nil, fmt.Errorf("hash surface %s: %w", s.Path, err)
		}
		out = append(out, ManifestEntry{Kind: s.Kind, Path: s.Path, Topic: s.Topic, SHA: sum})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

// RenderManifest emits the manifest as deterministic YAML.
//
// Hand-written and sorted, for the same reason the directive index is: Go
// randomises map iteration, and a file whose bytes move on identical input
// cannot be the thing freshness is measured against.
func RenderManifest(entries []ManifestEntry) string {
	var b strings.Builder
	b.WriteString("# edikt render manifest — generated by gov-compile, do not edit manually.\n")
	b.WriteString("# Every surface this compile produced, with the SHA-256 of its bytes.\n")
	b.WriteString("# NO TIMESTAMP, deliberately: this file must be byte-identical for byte-identical\n")
	b.WriteString("# input, or freshness checking cannot tell stale from recompiled.\n")
	b.WriteString("# The manifest cannot hash itself and is excluded from its own surface list.\n")
	b.WriteString("schema_version: 1\n")

	if len(entries) == 0 {
		// A measured zero, stated. `surfaces: []` says compile ran and produced
		// nothing; a MISSING file says compile did not run (INV-013).  edikt-guard:allow
		b.WriteString("surfaces: []\n")
		return b.String()
	}

	b.WriteString("surfaces:\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "  - path: %s\n", yamlQuote(e.Path))
		fmt.Fprintf(&b, "    kind: %s\n", yamlQuote(e.Kind))
		if e.Topic != "" {
			fmt.Fprintf(&b, "    topic: %s\n", yamlQuote(e.Topic))
		}
		fmt.Fprintf(&b, "    sha256: %s\n", yamlQuote(e.SHA))
	}
	return b.String()
}

// ParseManifest reads a manifest back.
//
// Deliberately a small hand parser over the shape RenderManifest emits, not a
// general YAML load: the consumers need path+sha and nothing else, and a
// permissive loader would happily accept a hand-edited manifest with extra
// keys — exactly the tampering INV-005 guards this file against.  edikt-guard:allow
func ParseManifest(body string) []ManifestEntry {
	var out []ManifestEntry
	var cur *ManifestEntry
	for _, line := range strings.Split(body, "\n") {
		t := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(t, "- path:"):
			if cur != nil {
				out = append(out, *cur)
			}
			cur = &ManifestEntry{Path: unquote(strings.TrimPrefix(t, "- path:"))}
		case cur != nil && strings.HasPrefix(t, "kind:"):
			cur.Kind = unquote(strings.TrimPrefix(t, "kind:"))
		case cur != nil && strings.HasPrefix(t, "topic:"):
			cur.Topic = unquote(strings.TrimPrefix(t, "topic:"))
		case cur != nil && strings.HasPrefix(t, "sha256:"):
			cur.SHA = unquote(strings.TrimPrefix(t, "sha256:"))
		}
	}
	if cur != nil {
		out = append(out, *cur)
	}
	return out
}

func unquote(s string) string {
	s = strings.TrimSpace(s)
	s = strings.TrimPrefix(s, `"`)
	s = strings.TrimSuffix(s, `"`)
	return s
}
