#!/bin/bash
set -euo pipefail
# PostToolUse hook: run verikt check --diff HEAD after file edits.
# Generated by verikt guide. Do not edit manually.

# Read the edited file path from stdin (JSON).
TOOL_INPUT=$(cat)
FILE_PATH=$(echo "$TOOL_INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Skip files matching check.exclude patterns.
case "$FILE_PATH" in
  */vendor/*|*/.git/*) exit 0 ;;
esac

# Run verikt check --diff HEAD scoped to changed files only.
RESULT=$(verikt check --diff HEAD -o json 2>/dev/null) || true
EXIT_CODE=$?

if [ "$EXIT_CODE" -eq 0 ]; then
  exit 0
fi

VIOLATIONS=$(echo "$RESULT" | jq -r '.violations | length // 0')
if [ "$VIOLATIONS" = "0" ] || [ "$VIOLATIONS" = "null" ]; then
  exit 0
fi

# Feed violations back as context for Claude to self-correct.
echo "{\"additionalContext\": \"verikt check --diff HEAD found $VIOLATIONS violation(s) after editing $FILE_PATH. Run verikt check --diff HEAD -o terminal for details.\"}"
exit 0
