package sidecar

import "testing"

// Every case below pins a SHAPE THE LIVE CORPUS PRODUCES, not a shape
// invented for the fixture. Where a case is marked "corpus:", the text is
// taken from a real sidecar. Four of these exist because the first version
// of this file passed against invented input and failed against production.

// ─── 2a. Standalone ───────────────────────────────────────────────────────

func TestClassifyStandalone(t *testing.T) {
	cases := []struct {
		name string
		text string
		want StandaloneVerdict
	}{
		// The ref tail must be stripped before the colon test, or a trailing
		// colon can never be seen — every compiled directive ends in "(ref: …)".
		{"trailing colon behind ref tail",
			"All integration tests in internal/rag/db_test.go MUST follow this pattern: (ref: ADR-001)",
			StandaloneTrailingColon},
		{"trailing colon bare",
			"The hook MUST emit the following fields:", StandaloneTrailingColon},

		{"corpus: as follows", // ADR-037[0]
			"The slash command `commands/gov/verify-diff.md` MUST construct the prompt body per directive as follows. (ref: ADR-037)",
			StandaloneDeixis},
		{"corpus: the four rules below", // ADR-029[0]
			"Tier-1 markdown commands MAY invoke tier-2 binaries via `bin/edikt <subcommand>` for orchestration purposes, provided the four rules below all hold. (ref: ADR-029)",
			StandaloneDeixis},
		{"corpus: this list", // ADR-029[6]
			"Adding a new orchestration verb to this list MUST require an ADR amending ADR-029. (ref: ADR-029)",
			StandaloneDeixis},
		{"the above", "The above MUST hold. (ref: ADR-001)", StandaloneDeixis},
		{"listed below", "Every path listed below MUST be validated. (ref: ADR-001)", StandaloneDeixis},

		// The positional matcher must not fire on ordinary English. "following"
		// as a temporal preposition points at nothing and is not deixis; an
		// earlier draft matched a bare "following" and would have failed here.
		{"temporal following is not deixis",
			"Following a failed dispatch, the runner MUST log to compile-errors.log. (ref: ADR-028)",
			StandaloneOK},
		{"follow as a verb is not deixis",
			"Every tier-1 command MUST follow the permit list. (ref: ADR-052)",
			StandaloneOK},
		{"named schema is not deixis",
			"`templates/schemas/gov-sidecar.v1.schema.json` MUST declare `body_digest` as optional. (ref: ADR-053)",
			StandaloneOK},
		{"colon mid-sentence is not a trailing colon",
			"The store MUST live at `$EDIKT_HOME/state/trusted-roots.json`: mode 0600. (ref: ADR-041)",
			StandaloneOK},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := ClassifyStandalone(c.text); got != c.want {
				t.Errorf("ClassifyStandalone() = %q, want %q\n  text: %s", got, c.want, c.text)
			}
		})
	}
}

// ─── 2b. MAY-level ────────────────────────────────────────────────────────

func TestIsMayLevel(t *testing.T) {
	cases := []struct {
		name string
		text string
		want bool
	}{
		{"corpus: doctor MAY treat", // ADR-007[3]
			"If `compile_schema_version` is missing, /edikt:doctor MAY treat governance as generated by v0.1.x. (ref: ADR-007)",
			true},
		{"corpus: MAY use it instead", // ADR-005[6]
			"If a rule override file exists at `.edikt/rules/{name}.md`, edikt MAY use it instead of the built-in pack. (ref: ADR-005)",
			true},

		// Strongest modal wins. A directive that says MAY somewhere but MUST
		// elsewhere is binding, and reporting it as MAY-level would call a
		// real rule a non-rule.
		{"MAY plus MUST is not MAY-level",
			"The v0.7.0 release MAY reconsider this in a new ADR, BUT only with evidence that MUST be recorded. (ref: ADR-032)",
			false},
		{"MUST NOT is not MAY-level",
			"MUST NOT fold prohibitions into `directives[]`. (ref: ADR-032)", false},

		// Lowercase "may" is ordinary English, not RFC-2119 permission.
		// Treating it as a modal would classify binding rules as non-rules.
		{"lowercase may is not a modal",
			"A stale list may refuse a valid model, so validation MUST be shape-only. (ref: ADR-054)",
			false},
		{"lowercase may with no other modal is still not MAY-level",
			"A vendor default change may alter the corpus. (ref: ADR-054)", false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := IsMayLevel(c.text); got != c.want {
				t.Errorf("IsMayLevel() = %v, want %v\n  text: %s", got, c.want, c.text)
			}
		})
	}
}

// ─── 2c. Normative force ──────────────────────────────────────────────────

func TestClassifyForce(t *testing.T) {
	cases := []struct {
		name             string
		directive, quote string
		want             ForceVerdict
	}{
		{"weakened: source MUST, directive SHOULD",
			"The evaluator SHOULD return BLOCKED when it cannot execute a step. (ref: ADR-010)",
			"The evaluator MUST return BLOCKED when it cannot execute a step.",
			ForceWeakened},
		{"weakened: source MUST, directive has no modal",
			"The evaluator returns BLOCKED when it cannot execute a step. (ref: ADR-010)",
			"The evaluator MUST return BLOCKED when it cannot execute a step.",
			ForceWeakened},

		// The four regressions that made the first corpus run report seven
		// findings where one was real. Directive and source carry the SAME
		// modal; only the case differs.
		{"corpus: lowercase never on both sides", // INV-011[1]
			"Absence of output is never evidence of completion. No exceptions. (ref: INV-011)",
			"Absence of output is never evidence of completion.",
			ForceMatch},
		{"corpus: lowercase must on both sides", // INV-002[8]
			"The new ADR must reference the superseded one (`Supersedes: ADR-NNN`). (ref: INV-002)",
			"The new ADR must reference the superseded one (`Supersedes: ADR-NNN`)",
			ForceMatch},

		// Attribution. The MUST belongs to a different sentence than the one
		// the directive renders, so there is nothing to compare and the
		// answer is UNMEASURED — not a weakening, and not a pass.
		{"corpus: MUST in an unrelated sentence of the quote", // ADR-040[14]
			"Changing the default adversary model requires an amending ADR. (ref: ADR-040)",
			"The adversary subagent template MUST declare `model: opus` per SPEC-009's locked choice. The model can be overridden per-run via `--adversary-model=<id>` for cost tuning, but the default is Opus 4.7.",
			ForceUnmeasured},
		// The bold marker after the period is what defeated the first
		// splitter: "execute.**" is a sentence end that does not look like one.
		{"corpus: sentence ends behind a bold marker", // ADR-010[6]
			"If an acceptance criterion requires Bash execution and Bash is denied, the verdict for that criterion MAY be BLOCKED. (ref: ADR-010)",
			"**The evaluator MUST NOT return PASS when required verification steps could not execute.** If an acceptance criterion requires Bash execution and Bash is denied, the verdict for that criterion is BLOCKED.",
			ForceUnmeasured},

		{"no force in source is unmeasured",
			"The compiler MUST stamp the version. (ref: ADR-054)",
			"The compiler stamps the version into every artifact.",
			ForceUnmeasured},
		{"empty quote is unmeasured",
			"The compiler MUST stamp the version. (ref: ADR-054)", "", ForceUnmeasured},
		{"no shared vocabulary is unmeasured",
			"The compiler MUST stamp the version. (ref: ADR-054)",
			"Sandboxes MUST be hermetic.",
			ForceUnmeasured},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := ClassifyForce(c.directive, c.quote); got != c.want {
				t.Errorf("ClassifyForce() = %q, want %q\n  directive: %s\n  quote: %s",
					got, c.want, c.directive, c.quote)
			}
		})
	}
}

// ─── 2d. Duplicates ───────────────────────────────────────────────────────

func TestDuplicateKey(t *testing.T) {
	// The live duplicate: ADR-030[0] and INV-012[0] state one rule, and
	// differ only in their ref tail.
	a := "Tier-2 Go binaries MUST NOT spawn, invoke, or shell out to any LLM CLI. (ref: ADR-030)"
	b := "Tier-2 Go binaries MUST NOT spawn, invoke, or shell out to any LLM CLI. (ref: INV-012)"
	if DuplicateKey(a) != DuplicateKey(b) {
		t.Errorf("ref tail must not affect the key:\n  %q\n  %q", DuplicateKey(a), DuplicateKey(b))
	}

	// Punctuation and backticks are formatting, not content.
	c := "Tier-2 Go binaries MUST NOT spawn, invoke, or shell out to any `LLM CLI`! (ref: ADR-030)"
	if DuplicateKey(a) != DuplicateKey(c) {
		t.Errorf("punctuation must not affect the key:\n  %q\n  %q", DuplicateKey(a), DuplicateKey(c))
	}

	// Different rules must not collide, or the check would report redundancy
	// that is not there.
	d := "Tier-1 markdown commands MUST NOT depend on tier-2 binaries. (ref: INV-001)"
	if DuplicateKey(a) == DuplicateKey(d) {
		t.Errorf("distinct rules collided on key %q", DuplicateKey(a))
	}
}
