package sidecar

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// realSidecarHeader is a VERBATIM copy of the header every sidecar in this
// repo's own corpus and the annotakt fixture corpus actually carries — a
// 4-line `#` comment block, then a BLANK line, then `schema_version:`. This
// is load-bearing: go-yaml attaches a head comment separated from its
// following node by a blank line to the DOCUMENT node (root.HeadComment),
// not to the mapping's first key (doc.Content[0].HeadComment). An earlier
// version of this test used a single comment line directly above
// schema_version with NO blank line — a shape that occurs nowhere in a real
// corpus — which attaches to doc.Content[0] instead, and the fix's first
// version only checked that location. All three tests passed; the rewrite
// did nothing on any real file (44 of 50 sidecars in the annotakt fixture
// stayed at v1 after a successful `migrate to-v2` run). Verified directly:
// `migrate to-v2` run against a real-shaped file, then the bytes on disk
// read back — not just asserted through this test, which is exactly the
// class of check that hid the defect the first time.
const realSidecarHeader = `# yaml-language-server: $schema=../../../templates/schemas/gov-sidecar.%s.schema.json
# Governance sidecar — co-located with an ADR / invariant / guideline .md.
# Generated by the sidecar-extractor agent. Edit prose in the parent .md,
# then re-run /edikt:<artifact>:compile to regenerate this file.
`

// This is the positive case: a real v1 sidecar carrying the
// yaml-language-server $schema hint that annotakt's fixture corpus showed
// `migrate to-v2` leaving stale on 44 of 50 sidecars — schema_version bumped,
// source_excerpt renamed, but the editor hint still pointing an IDE at the
// v1 schema, which then reports source_excerpts as an unknown field.
func TestConvertFileToV2_RewritesStaleSchemaHint(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "ADR-100-x.edikt.yaml")
	raw := strings.Replace(realSidecarHeader, "%s", "v1", 1) + `
schema_version: 1
topic: hooks
path: docs/architecture/decisions/ADR-100-x.md
signals:
  - hook
directives:
  - text: "Hooks must emit JSON."
    source_excerpt:
      line_start: 1
      line_end: 1
      quote: "Hooks must emit JSON."
`
	if err := os.WriteFile(path, []byte(raw), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	changed, err := ConvertFileToV2(path)
	if err != nil {
		t.Fatalf("ConvertFileToV2: %v", err)
	}
	if !changed {
		t.Fatal("expected changed=true")
	}

	out, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read result: %v", err)
	}
	s := string(out)
	if strings.Contains(s, "gov-sidecar.v1.schema.json") {
		t.Fatalf("stale v1 schema hint survived conversion:\n%s", s)
	}
	if !strings.Contains(s, "gov-sidecar.v2.schema.json") {
		t.Fatalf("expected the hint rewritten to point at v2:\n%s", s)
	}
	if !strings.Contains(s, "source_excerpts:") {
		t.Fatalf("expected the usual v2 shape conversion to still happen:\n%s", s)
	}
}

// Same case, but with the comment directly above schema_version and NO
// blank line — the shape that attaches to doc.Content[0] rather than
// root.HeadComment. Rarer, unconfirmed in any real corpus file examined,
// but the code has a rung for it and that rung needs its own coverage
// rather than being the only shape under test, which is what happened
// before.
func TestConvertFileToV2_RewritesStaleSchemaHint_NoBlankLineVariant(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "ADR-101-x.edikt.yaml")
	raw := `# yaml-language-server: $schema=../../../templates/schemas/gov-sidecar.v1.schema.json
schema_version: 1
topic: hooks
path: docs/architecture/decisions/ADR-101-x.md
signals:
  - hook
directives:
  - text: "Hooks must emit JSON."
    source_excerpt:
      line_start: 1
      line_end: 1
      quote: "Hooks must emit JSON."
`
	if err := os.WriteFile(path, []byte(raw), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	changed, err := ConvertFileToV2(path)
	if err != nil {
		t.Fatalf("ConvertFileToV2: %v", err)
	}
	if !changed {
		t.Fatal("expected changed=true")
	}

	out, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read result: %v", err)
	}
	s := string(out)
	if strings.Contains(s, "gov-sidecar.v1.schema.json") {
		t.Fatalf("stale v1 schema hint survived conversion (no-blank-line variant):\n%s", s)
	}
	if !strings.Contains(s, "gov-sidecar.v2.schema.json") {
		t.Fatalf("expected the hint rewritten to point at v2 (no-blank-line variant):\n%s", s)
	}
}

// Negative/control: a sidecar with no yaml-language-server hint at all must
// not gain one — this migration edits an existing stale hint, it does not
// invent a new comment where none existed.
func TestConvertFileToV2_NoHintNoInsertion(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "ADR-200-y.edikt.yaml")
	raw := `schema_version: 1
topic: hooks
path: docs/architecture/decisions/ADR-200-y.md
signals:
  - hook
directives:
  - text: "Hooks must emit JSON."
    source_excerpt:
      line_start: 1
      line_end: 1
      quote: "Hooks must emit JSON."
`
	if err := os.WriteFile(path, []byte(raw), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	changed, err := ConvertFileToV2(path)
	if err != nil {
		t.Fatalf("ConvertFileToV2: %v", err)
	}
	if !changed {
		t.Fatal("expected changed=true (schema_version + anchor still convert)")
	}

	out, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read result: %v", err)
	}
	if strings.Contains(string(out), "yaml-language-server") {
		t.Fatalf("a schema hint appeared where none existed before:\n%s", out)
	}
}

// Control: a v2 sidecar whose hint already points at v2 must not be touched
// or reported changed by the hint check — idempotency holds independent of
// the source_excerpts/schema_version rungs, which already cover this file.
// Uses the real header shape (block + blank line), matching what an
// already-migrated real sidecar actually looks like on disk.
func TestConvertFileToV2_AlreadyV2HintUntouched(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "ADR-300-z.edikt.yaml")
	raw := strings.Replace(realSidecarHeader, "%s", "v2", 1) + `
schema_version: 2
topic: hooks
path: docs/architecture/decisions/ADR-300-z.md
signals:
  - hook
directives:
  - text: "Hooks must emit JSON."
    source_excerpts:
      - line_start: 1
        line_end: 1
        quote: "Hooks must emit JSON."
`
	if err := os.WriteFile(path, []byte(raw), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	changed, err := ConvertFileToV2(path)
	if err != nil {
		t.Fatalf("ConvertFileToV2: %v", err)
	}
	if changed {
		t.Fatal("expected changed=false — already v2 in both shape and hint")
	}
}

// Asserts the exact first line of the rewritten file, rather than only
// substring presence/absence — a stricter check than the tests above, kept
// deliberately separate as this defect class's own regression guard.
func TestConvertFileToV2_RealHeaderShape_ExactBytes(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "ADR-400-w.edikt.yaml")
	header := strings.Replace(realSidecarHeader, "%s", "v1", 1)
	raw := header + `
schema_version: 1
topic: hooks
path: docs/architecture/decisions/ADR-400-w.md
signals:
  - hook
directives:
  - text: "Hooks must emit JSON."
    source_excerpt:
      line_start: 1
      line_end: 1
      quote: "Hooks must emit JSON."
`
	if err := os.WriteFile(path, []byte(raw), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	if _, err := ConvertFileToV2(path); err != nil {
		t.Fatalf("ConvertFileToV2: %v", err)
	}

	out, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read result: %v", err)
	}
	firstLine := strings.SplitN(string(out), "\n", 2)[0]
	want := "# yaml-language-server: $schema=../../../templates/schemas/gov-sidecar.v2.schema.json"
	if firstLine != want {
		t.Fatalf("first line of the rewritten file:\n  got:  %q\n  want: %q", firstLine, want)
	}
}
